### ISSUE TITLE
ReSharper 2016 support

### ISSUE THREAD

**Issue by DixonDs** [aelij/ConfigureAwaitChecker#10]
Please, release a version for new ReSharper release :)

**Comment by jimmymain** [comment]
:+1: yea, please, so easy to forget these without the plugin...

**Comment by reisenberger** [comment]
:+1: a very useful extension!

**Comment by aelij** [comment]
Done :)

**Comment by jimmymain** [comment]
you rock!

**Comment by reisenberger** [comment]
Kudos for the quick fix! :+1:
