### ISSUE TITLE
No warning in Owin middleware

### ISSUE THREAD

**Issue by jchannon** [aelij/ConfigureAwaitChecker#11]
I've just been recommended this extension and loaded up this solution and I get no warning about `ConfigureAwait` here https://github.com/VQComms/TracingMiddleware/blob/master/src/TracingMiddleware/TracingMiddleware.cs#L57

Any ideas?

**Comment by aelij** [comment]
Does it show in other places?

**Comment by jchannon** [comment]
No :(

**Comment by aelij** [comment]
Which version of ReSharper are you using? EAPs are not supported by the plugin.

**Comment by jchannon** [comment]
10.0.2 is my version

**Comment by aelij** [comment]
Can you make sure the plugin is installed and running? I think you can check the logs at `%LOCALAPPDATA%\JetBrains\Shared\v05\InstallerLog`. It should work for v10.0.2.

**Comment by aelij** [comment]
You can also produce a runtime log by running `devenv /ReSharper.LogFile`. The logs will be saved in `%TEMP%\JetLogs`.

**Comment by aelij** [comment]
Closing until new info is added.
