### ISSUE TITLE
The following code pattern does not detect ConfigureAwait use. 

### ISSUE THREAD

**Issue by mgi2212** [aelij/ConfigureAwaitChecker#18]
var returnClause = new[] { "discoveryJson", "IsDiscoverable" };
                dynamic whereClause = new ExpandoObject();
                whereClause.TypeOf = AlexaApplianceClassPath;
                int count = 0;
                var devices = await HomeObject.Select(returnClause, whereClause).ConfigureAwait(false);

**Comment by aelij** [comment]
Hi @mgi2212. Could you provide a complete sample? I can't compile this.

**Comment by aelij** [comment]
Closing. Please reopen if it's still relevant.
