### ISSUE TITLE
Rider support

### ISSUE THREAD

**Issue by matkoch** [aelij/ConfigureAwaitChecker#19]
Hey @aelij,

thanks for this great extension. I'm wondering if we could start adding support for Rider as well... I can even help with that if you're interested.

Please let me know what you think.
Matt

**Comment by aelij** [comment]
Hey Matt,

You're welcome to submit a PR. Does Rider use the same extension SDK as ReSharper?

Eli.

**Comment by aelij** [comment]
Plugin uploaded to gallery: https://plugins.jetbrains.com/plugin/10948-configureawait-checker (still pending approval)

Thanks, @Socolin!
