### ISSUE TITLE
2018.1 Support

### ISSUE THREAD

**Issue by IvanKonov** [aelij/ConfigureAwaitChecker#20]
Add 2018.1 support please

**Comment by SimonCropp** [comment]
made an attempt here https://github.com/aelij/ConfigureAwaitChecker/pull/21

**Comment by aelij** [comment]
Published v0.13. Thanks @SimonCropp

**Comment by SimonCropp** [comment]
Thank you :)

**Comment by SimonCropp** [comment]
Although it is weird 10 people up voted this request without spending the 10 min to submit the PR to achieve it
