### ISSUE TITLE
In VS 15.8 pre-2 the context action doesn't add the configure await fix

### ISSUE THREAD

**Issue by DoCode** [aelij/ConfigureAwaitChecker#22]

**Comment by aelij** [comment]
Hmm, not sure what I can do about that, I'm just using ReSharper APIs. I'd appreciate it if someone could test this with the latest ReSharper EAP (it would probably require compiling a local version of the ConfigureAwaitChecker, updated to use the latest preview SDK).

**Comment by DoCode** [comment]
Hmmm... I checked the VS 15.7.4 and it's the same issue:
![configure-await-not-working](https://user-images.githubusercontent.com/1489133/41819484-6d05a6a0-77c1-11e8-9571-0d0dec3f3862.gif)

**Comment by DoCode** [comment]
@aelij is the VS15.7.4 working on your machine?

**Comment by johnpedersen-freightways** [comment]
Have the same problem with VS15.7.4 an R#2018.1.2. It hasn't worked for me at all in the 2018 wave.

**Comment by johnpedersen-freightways** [comment]
I have done a bit of debugging. It seems that the delegate to Transactions.Execute is never called. I don't know much about R# plugin development so not sure why that is happening or how to fix it. It's not throwing an exception. The execute call returns a result indicating failure.

``ConsiderUsingConfigureAwaitQuickFix.cs:68``

Internally the execute call is catching an exception: `` "Method not found: UsingWriteLock"``
It seems that the JIT is failing when processing the delegate.

**Comment by johnpedersen-freightways** [comment]
Updating to the latest R# SDK fixed the problem for me.

**Comment by aelij** [comment]
@johnendev Wanna submit a PR?

**Comment by aelij** [comment]
New package v0.14 pushed
