### ISSUE TITLE
R# 9.1 support

### ISSUE THREAD

**Issue by winseros** [aelij/ConfigureAwaitChecker#3]
Hey, I've noticed this awesome extension is missing for R#9.1, but still available for 9.0 and 8; Any chance to see it for 9.1?

**Comment by aelij** [comment]
Sure. I'll work on it when I find the time.

**Comment by aelij** [comment]
I closed this issue after publishing the package, but I found out it wasn't available in the Extension Manager. Now I've uploaded it again, and it's fixed. Enjoy!

**Comment by winseros** [comment]
Thx!
