### ISSUE TITLE
Add support for Rider 2019.3+ (EAP included)

### ISSUE THREAD

**Issue by VagyokC4** [aelij/ConfigureAwaitChecker#33]
I noticed I cannot use this plugin in EAP versions, only in the non-EAP version, and now with 2019.3, it's not supported either.

As opposed to needing to keep updating the version numbers every time a new build is released, why not open up this plugin to all future version + EAP, and then only fix when something breaks in a future version?

**Comment by yevgeniyredko** [comment]
https://www.jetbrains.com/help/resharper/sdk/Extensions/PlatformVersioning.html

> ReSharper does not maintain backwards binary compatibility between major or minor releases.

**Comment by aelij** [comment]
@yevgeniyredko is correct. If someone wants to contribute a version during EAP I will merge it.
