### ISSUE TITLE
Update to latest version of rider IDE.

### ISSUE THREAD

**Issue by rafek1241** [aelij/ConfigureAwaitChecker#39]

**Comment by emanuelbalea** [comment]
if you care to try it offline see my pr for a offline compiled version. Would need to wait for Repo owner to review/publish for it to be available in the marketplace.

**Comment by rafek1241** [comment]
@emanuelbalea I will, thank you

**Comment by rafek1241** [comment]
@emanuelbalea
I tested that and works like a charm 👍
