### ISSUE TITLE
Support for 2020.2

### ISSUE THREAD

**Issue by WS68** [aelij/ConfigureAwaitChecker#42]
Hi,

It seems ConfigureAwaitChecker 0.22.0 doesn't work on R# 2020.2. Could you please support this version?

Regards,
Vladimir.

**Comment by novama** [comment]
Hi, I am having the same issue since yesterday when I udpated Resharper. I noticed I lost all the extensions I used to have installed then I installed them back but the ConfigureAwaitChecker is not working any more.

Regards and thanks in advance,
Norman

**Comment by yevgeniyredko** [comment]
Fixed by #41
