### ISSUE TITLE
Update ConfigureAwaitChecker plugin to rider & resharper 2020.3

### ISSUE THREAD

**Issue by rafek1241** [aelij/ConfigureAwaitChecker#44]

**Comment by yevgeniyredko** [comment]
Updated in https://github.com/aelij/ConfigureAwaitChecker/pull/43

**Comment by DawidIzydor** [comment]
Could you update it on the plugin site? The newest version there does not support 2020.3

https://plugins.jetbrains.com/plugin/11632-resharper-configureawait-checker/versions

**Comment by aelij** [comment]
Fixed in #43 (might take a couple of days to get approved)
