### ISSUE TITLE
ReSharper and ConfigureAwaitChecker versioning

### ISSUE THREAD

**Issue by square-unit** [aelij/ConfigureAwaitChecker#46]
Hi guys,

I'm a support engineer of the ReSharper team. The latest ConfigureAwaitChecker version is marked as compatible with all the versions newer than Wave 203 `Wave:203.0.0` However, it requests for Wave 203 components when being installed into Wave 211 (2021.1 EAP)

So it is available in R# Extension Manager despite it causes the related errors during the installation and when it's running in ReSharper.

>“Error resolving type JetBrains.ReSharper.Feature.Services.CSharp.Analyses.Bulbs.ICSharpContextActionDataProvider from assembly “JetBrains.ReSharper.Feature.Services.CSharp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Feature.Services.CSharp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”. Could not find the type by its FQN. Is assembly qualification specified? True! Is it of our own assembly? True! Is looking into referenced assemblies allowed? False! Was the qualified referenced assembly encountered during lookup? False! Tried loading an implicitly-referenced assembly? False! Were following a forwarder exported type's assembly ref? No!”

>“Error resolving type JetBrains.ReSharper.Feature.Services.Intentions.Scoped.QuickFixes.ScopedQuickFixBase from assembly “JetBrains.ReSharper.Feature.Services, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Feature.Services, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”. Could not find the type by its FQN. Is assembly qualification specified? True! Is it of our own assembly? True! Is looking into referenced assemblies allowed? False! Was the qualified referenced assembly encountered during lookup? False! Tried loading an implicitly-referenced assembly? False! Were following a forwarder exported type's assembly ref? No!”

Please fix the versioning issue and upload the updated version with properly specified supported R# version: `Wave:[203.0.0]`

**Comment by square-unit** [comment]
We'll remove the extension from the ReSharper Gallery. Please fix the versioning issue and upload the updated version with properly specified supported R# versions. It will become available in the Extension Manager of all the compatible R# builds.

**Comment by aelij** [comment]
@square-unit Could you please submit a PR to fix this issue? I no longer actively maintain this extension.

**Comment by yevgeniyredko** [comment]
@aelij I'll fix it today

**Comment by yevgeniyredko** [comment]
fixed in https://github.com/aelij/ConfigureAwaitChecker/pull/47

**Comment by MPleskunina** [comment]
Please do not forget to upload the update to the marketplace. As far as I know, @aelij has the "Upload Update" option there.
